services:
  backend:
    build: ./backend
    container_name: hackstrom_backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
      - DATABASE_URL=sqlite:///./data/hackstrom.db
      - UPLOAD_DIR=uploads
      - REDIS_URL=redis://redis:6379/0
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: hackstrom_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hackstrom_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker1:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: hackstrom_worker_1
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - uploads_data:/app/uploads
      - tmp_data:/tmp
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker2:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: hackstrom_worker_2
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - uploads_data:/app/uploads
      - tmp_data:/tmp
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  flower:
    image: mher/flower:2.0
    container_name: hackstrom_flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: hackstrom_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: hackstrom_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=hackstrom2026
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./backend/grafana/provisioning:/etc/grafana/provisioning
      - ./backend/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  uploads_data:
  db_data:
  tmp_data:
  grafana_data:
